### ISSUE TITLE
yotta Command not available.

### ISSUE THREAD

**Issue by zfm076** [lancaster-university/microbit-dal#458]
**(1).pip3 install yotta**
**(2).yotta -v  The error message is as follows:**
PS E:\Microbit_Freertos\microbit-samples> yotta -v
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.3 (c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages), Requirement.parse('cryptography>=2.8'), {'pyOpenSSL'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts\yotta-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.3 (c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages), Requirement.parse('cryptography>=2.8'), {'pyOpenSSL'})

**(3).then I think the cryptography version is too low. So,I upgrade cryptography:pip3 install yotta --upgrade cryptography. then.There was another mistake:  yotta 0.20.0 has requirement cryptography<=2.3,>=2.1.4, but you'll have cryptography 2.8 which is incompatible.**

PS E:\HWJ_Microbit_Freertos\microbit-samples> pip3 install yotta --upgrade cryptography
Requirement already up-to-date: yotta in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (0.20.0)
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/2a/e2/c97b90d6dcd9d55c1a9bc4e387c79a10e3b1050e44ae6a79245cab5562fc/cryptography-2.8-cp36-cp36m-win32.whl
Requirement not upgraded as not directly required: semantic_version<3,>=2.3.1 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (2.8.4)
Requirement not upgraded as not directly required: requests[security]<3,>=2.4.3 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (2.22.0)
Requirement not upgraded as not directly required: certifi>=2016.2.28 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (2019.9.11)
Requirement not upgraded as not directly required: PyGithub<2,>=1.25 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (1.45)
Requirement not upgraded as not directly required: colorama<0.4,>=0.3 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (0.3.9)
Requirement not upgraded as not directly required: hgapi<2,>=1.7 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (1.7.4)
Requirement not upgraded as not directly required: Jinja2<3,>=2.7.0 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (2.10.3)
Requirement not upgraded as not directly required: PyJWT<2.0,>=1.0 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from
yotta) (1.7.1)
Requirement not upgraded as not directly required: pathlib<1.1,>=1.0.1 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (1.0.1)
Requirement not upgraded as not directly required: jsonschema<3.0,>=2.4.0 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (2.6.0)
Requirement not upgraded as not directly required: argcomplete<2.0,>=0.8.0 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (1.11.0)
Requirement not upgraded as not directly required: mbed_test_wrapper<2.0.0,>=0.0.3 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (1.0.0)
Requirement not upgraded as not directly required: valinor<2.0,>=1.1.4 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (1.1.4)
Requirement not upgraded as not directly required: intelhex<3.0,>=2.0 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from yotta) (2.2.1)
Requirement not upgraded as not directly required: jsonpointer<2.0,>=1.9 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages
(from yotta) (1.14)
Requirement not upgraded as not directly required: ntfsutils<0.2,>=0.1.3 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages
(from yotta) (0.1.4)
Requirement not upgraded as not directly required: six>=1.4.1 in c:\users\administrator\appdata\roaming\python\python36\site-packages (from cryptography) (1.12.0)
Requirement not upgraded as not directly required: cffi!=1.11.3,>=1.8 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from cryptography) (1.13.2)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages
(from requests[security]<3,>=2.4.3->yotta) (3.0.4)
Requirement not upgraded as not directly required: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from requests[security]<3,>=2.4.3->yotta) (1.25.3)
Requirement not upgraded as not directly required: idna<2.9,>=2.5 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from requests[security]<3,>=2.4.3->yotta) (2.8)
Requirement not upgraded as not directly required: pyOpenSSL>=0.14; extra == "security" in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from requests[security]<3,>=2.4.3->yotta) (19.1.0)
Requirement not upgraded as not directly required: deprecated in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from PyGithub<2,>=1.25->yotta) (1.2.7)
Requirement not upgraded as not directly required: MarkupSafe>=0.23 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from Jinja2<3,>=2.7.0->yotta) (1.1.1)
Requirement not upgraded as not directly required: importlib-metadata<2,>=0.23; python_version == "3.6" in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from argcomplete<2.0,>=0.8.0->yotta) (1.3.0)
Requirement not upgraded as not directly required: pyyaml<6.0,>=5.1 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from valinor<2.0,>=1.1.4->yotta) (5.3)
Requirement not upgraded as not directly required: setuptools in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from valinor<2.0,>=1.1.4->yotta) (39.0.1)
Requirement not upgraded as not directly required: pyOCD<1.0,>=0.3 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from
valinor<2.0,>=1.1.4->yotta) (0.24.1)
Requirement not upgraded as not directly required: project_generator<0.9.0,>=0.8.0 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from valinor<2.0,>=1.1.4->yotta) (0.8.17)
Requirement not upgraded as not directly required: pyelftools==0.23 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from valinor<2.0,>=1.1.4->yotta) (0.23)
Requirement not upgraded as not directly required: pycparser in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography) (2.19)
Requirement not upgraded as not directly required: wrapt<2,>=1.10 in c:\users\administrator\appdata\roaming\python\python36\site-packages (from deprecated->PyGithub<2,>=1.25->yotta) (1.11.1)
Requirement not upgraded as not directly required: zipp>=0.5 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from importlib-metadata<2,>=0.23; python_version == "3.6"->argcomplete<2.0,>=0.8.0->yotta) (0.6.0)
Requirement not upgraded as not directly required: cmsis-pack-manager>=0.2.7 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (0.2.9)
Requirement not upgraded as not directly required: pywinusb>=0.4.0; platform_system == "Windows" in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (0.4.2)
Requirement not upgraded as not directly required: intervaltree<4.0,>=3.0.2 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (3.0.2)
Requirement not upgraded as not directly required: pyusb<2.0,>=1.0.0b2 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (1.0.2)
Requirement not upgraded as not directly required: prettytable in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (0.7.2)
Requirement not upgraded as not directly required: argparse in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from project_generator<0.9.0,>=0.8.0->valinor<2.0,>=1.1.4->yotta) (1.4.0)
Requirement not upgraded as not directly required: xmltodict in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from project_generator<0.9.0,>=0.8.0->valinor<2.0,>=1.1.4->yotta) (0.12.0)
Requirement not upgraded as not directly required: project_generator_definitions<0.3.0,>=0.2.2 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from project_generator<0.9.0,>=0.8.0->valinor<2.0,>=1.1.4->yotta) (0.2.40)
Requirement not upgraded as not directly required: more-itertools in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from zipp>=0.5->importlib-metadata<2,>=0.23; python_version == "3.6"->argcomplete<2.0,>=0.8.0->yotta) (8.0.2)
Requirement not upgraded as not directly required: appdirs>=1.4 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from cmsis-pack-manager>=0.2.7->pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (1.4.3)
Requirement not upgraded as not directly required: milksnake>=0.1.2 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from cmsis-pack-manager>=0.2.7->pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (0.1.5)
Requirement not upgraded as not directly required: sortedcontainers<3.0,>=2.0 in c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages (from intervaltree<4.0,>=3.0.2->pyOCD<1.0,>=0.3->valinor<2.0,>=1.1.4->yotta) (2.1.0)
yotta 0.20.0 has requirement cryptography<=2.3,>=2.1.4, but you'll have cryptography 2.8 which is incompatible.
Installing collected packages: cryptography
  Found existing installation: cryptography 2.3
    Uninstalling cryptography-2.3:
      Successfully uninstalled cryptography-2.3
Successfully installed cryptography-2.8
PS E:\Microbit_Freertos\microbit-samples>

**(4)I don't know how to make my yotta work anymore.Do you have any ideas?**

**Comment by zfm076** [comment]
I solved the problem by:  pip3 install pyOpenSSL==19.0.0

**Comment by zfm076** [comment]
But,Other problems arose:

PS E:\Microbit_Freertos\microbit-samples> yt clean
PS E:\Microbit_Freertos\microbit-samples> yt build
info: get versions for bbc-microbit-classic-gcc
info: download bbc-microbit-classic-gcc@0.2.3 from the public module registry
info: get versions for mbed-gcc
info: download mbed-gcc@0.1.3 from the public module registry
warning: The build target has not been set, so the default (bbc-microbit-classic-gcc,*) is being used. You can use `yotta target <targetname>` to set the build target. See http://docs.yottabuild.org/tutorial/targets.html for more information on using targets.
info: get versions for microbit
**error: maximum recursion depth exceeded in comparison**
PS E:\Microbit_Freertos\microbit-samples>

**Comment by zfm076** [comment]
> But,Other problems arose:
> 
> PS E:\Microbit_Freertos\microbit-samples> yt clean
> PS E:\Microbit_Freertos\microbit-samples> yt build
> info: get versions for bbc-microbit-classic-gcc
> info: download bbc-microbit-classic-gcc@0.2.3 from the public module registry
> info: get versions for mbed-gcc
> info: download mbed-gcc@0.1.3 from the public module registry
> warning: The build target has not been set, so the default (bbc-microbit-classic-gcc,*) is being used. You can use `yotta target <targetname>` to set the build target. See http://docs.yottabuild.org/tutorial/targets.html for more information on using targets.
> info: get versions for microbit
> **error: maximum recursion depth exceeded in comparison**
> PS E:\Microbit_Freertos\microbit-samples>

The reason is that the network is bad, so it takes too long to get versions for microbit.
